# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab3a3d053cbe1a9198b5da9adaf2102cd52a94a27d3468775ab9924ec7035d6c8a741ca7efd43779c03620d2b8a0721bc1eafe0b1a4674188f2a7a4f142bdd27

test:
  secret_key_base: 92396ea797353c9d3cb87444fa5cf730b97260dbf7e9d4afdc2c089b4af774aef78afd901ad3ad27af8dca1f63d31f4f7ee8d245b665a06de9e95d7805612d24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
